# Generated by Django 4.2.7 on 2026-06-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0007_alter_documenttemplate_template_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-start_date', 'name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='extended_contract_end_date',
            field=models.DateField(blank=True, help_text='New end date if contract is extended', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_contract_extended',
            field=models.BooleanField(default=False, help_text='Indicates if the contract period has been extended'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='probation_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Ending Soon', 'Ending Soon'), ('Completed', 'Completed'), ('Extended', 'Extended'), ('Rejected', 'Rejected')], default='Active', max_length=20),
        ),
    ]
