# Generated by Django 4.2.7 on 2026-07-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0010_employee_is_contract_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProbationReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.DateField(help_text='First day of the month covered by the report')),
                ('department_name', models.CharField(max_length=100)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('test_mode', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_portal.department')),
            ],
            options={
                'ordering': ['-sent_at', 'department_name'],
                'indexes': [models.Index(fields=['report_month', 'department_name', 'test_mode'], name='hr_portal_m_report__5cbf6d_idx')],
            },
        ),
    ]
